import CoreGraphics
import SwiftUI

// Generated by Scripts/generate-logo.py. Edit the artwork, not this file.

/// CueWavePath — Cue's mark for the plaque and the panel, read from Resources/CueWave.svg.
///
/// The artwork itself, exactly as drawn. Nothing here is mirrored, reordered or
/// rebuilt: the generator flattens the group transforms and normalises the
/// result, and that is all.
///
/// Coordinates are normalised into a unit box with y increasing downward, so
/// the mark can be drawn at any size in either coordinate system.
///
/// `nonisolated` because `Shape.path(in:)` is, and geometry has no business
/// belonging to an actor: these are constants and a pure function of a
/// rectangle.
nonisolated enum CueWavePath {
    /// Width divided by height, for callers that need to reserve space.
    static let aspect: CGFloat = 0.97047

    /// One shape per element.
    ///
    /// Each is a flat run of coordinates: the first pair is the starting point,
    /// and every six numbers after it are a cubic curve — two control points and
    /// an end point. Every shape closes.
    static let shapes: [[CGFloat]] = [
        [0.49687, 0.00082, 0.50739, 0.00000, 0.51484, 0.01020, 0.51844, 0.01868, 0.53713, 0.06262, 0.54499, 0.11426, 0.55090, 0.16130, 0.56473, 0.27143, 0.56913, 0.38313, 0.56918, 0.49400, 0.56997, 0.59313, 0.56569, 0.69225, 0.55637, 0.79097, 0.55073, 0.84771, 0.54273, 0.91129, 0.52507, 0.96583, 0.52112, 0.97803, 0.51422, 0.99391, 0.50177, 0.99980, 0.46830, 1.00000, 0.45194, 0.86527, 0.44850, 0.83843, 0.43801, 0.75074, 0.43217, 0.66259, 0.43100, 0.57432, 0.42820, 0.46218, 0.43136, 0.34996, 0.44046, 0.23813, 0.44417, 0.19572, 0.45908, 0.02089, 0.49687, 0.00082],
        [0.64368, 0.03358, 0.67385, 0.03458, 0.68816, 0.15975, 0.69133, 0.18587, 0.70056, 0.26767, 0.70575, 0.34985, 0.70688, 0.43213, 0.70961, 0.54726, 0.70579, 0.66244, 0.69545, 0.77715, 0.69032, 0.82880, 0.68331, 0.88619, 0.66771, 0.93601, 0.66442, 0.94650, 0.65824, 0.96135, 0.64761, 0.96653, 0.63853, 0.96635, 0.63374, 0.96025, 0.63036, 0.95266, 0.61233, 0.91226, 0.60562, 0.86218, 0.60018, 0.81884, 0.59065, 0.73687, 0.58530, 0.65450, 0.58414, 0.57203, 0.58137, 0.45746, 0.58499, 0.34284, 0.59496, 0.22866, 0.60009, 0.17518, 0.60724, 0.11527, 0.62347, 0.06375, 0.62680, 0.05317, 0.63293, 0.03875, 0.64368, 0.03358],
        [0.35213, 0.03362, 0.38173, 0.03331, 0.39654, 0.15807, 0.39953, 0.18314, 0.41189, 0.28678, 0.41606, 0.39205, 0.41606, 0.49637, 0.41666, 0.59358, 0.41228, 0.69077, 0.40293, 0.78756, 0.39922, 0.82306, 0.39449, 0.86000, 0.38701, 0.89495, 0.38303, 0.91357, 0.37428, 0.95814, 0.35594, 0.96658, 0.32566, 0.96644, 0.31133, 0.84040, 0.30828, 0.81556, 0.29807, 0.72502, 0.29271, 0.63403, 0.29223, 0.54295, 0.29077, 0.44790, 0.29368, 0.35282, 0.30094, 0.25801, 0.30422, 0.21727, 0.31764, 0.05135, 0.35213, 0.03362],
        [0.22275, 0.09184, 0.24438, 0.09035, 0.25503, 0.17999, 0.25687, 0.19501, 0.27101, 0.30608, 0.27348, 0.42517, 0.27281, 0.53662, 0.27247, 0.59396, 0.26589, 0.88025, 0.22715, 0.90856, 0.20558, 0.91073, 0.19476, 0.81827, 0.19275, 0.80270, 0.18549, 0.74222, 0.18093, 0.68147, 0.17909, 0.62060, 0.17642, 0.54606, 0.17623, 0.47147, 0.17852, 0.39692, 0.18006, 0.34831, 0.18876, 0.11516, 0.22275, 0.09184],
        [0.77226, 0.09184, 0.77602, 0.09165, 0.77983, 0.09283, 0.78170, 0.09622, 0.79639, 0.12367, 0.80270, 0.16187, 0.80608, 0.19269, 0.82871, 0.39878, 0.82909, 0.61111, 0.80477, 0.81706, 0.80236, 0.83742, 0.79324, 0.89642, 0.77667, 0.90855, 0.77297, 0.90870, 0.76887, 0.90740, 0.76711, 0.90410, 0.75192, 0.87568, 0.74624, 0.83524, 0.74244, 0.80402, 0.72878, 0.69198, 0.72559, 0.57724, 0.72667, 0.46464, 0.72711, 0.40880, 0.72916, 0.35298, 0.73283, 0.29725, 0.73534, 0.26007, 0.74561, 0.11045, 0.77226, 0.09184],
        [0.11048, 0.19393, 0.11196, 0.19419, 0.11302, 0.19439, 0.11413, 0.19542, 0.12894, 0.20911, 0.13532, 0.32453, 0.13666, 0.35025, 0.13926, 0.40162, 0.14058, 0.45304, 0.14061, 0.50448, 0.14071, 0.55143, 0.13820, 0.79115, 0.11298, 0.81823, 0.11143, 0.81813, 0.11032, 0.81799, 0.10913, 0.81692, 0.09125, 0.80096, 0.08530, 0.63784, 0.08437, 0.60666, 0.08283, 0.55753, 0.08239, 0.50836, 0.08304, 0.45922, 0.08353, 0.41801, 0.08790, 0.21716, 0.11048, 0.19393],
        [0.88662, 0.19394, 0.88824, 0.19423, 0.88941, 0.19461, 0.89064, 0.19573, 0.91021, 0.21349, 0.91560, 0.41065, 0.91620, 0.44525, 0.91721, 0.50401, 0.91782, 0.78944, 0.88884, 0.81851, 0.88769, 0.81820, 0.88650, 0.81787, 0.88557, 0.81710, 0.87190, 0.80573, 0.86529, 0.70366, 0.86386, 0.68059, 0.86167, 0.64314, 0.86020, 0.60565, 0.85946, 0.56815, 0.85857, 0.51079, 0.85778, 0.22551, 0.88662, 0.19394],
        [0.97598, 0.34846, 0.99893, 0.35375, 1.00000, 0.63729, 0.97756, 0.66416, 0.95451, 0.65490, 0.95449, 0.37583, 0.97598, 0.34846],
        [0.02166, 0.34850, 0.04527, 0.36820, 0.04433, 0.63865, 0.02323, 0.66414, 0.00000, 0.65475, 0.00036, 0.37527, 0.02166, 0.34850],
    ]

    /// The whole mark, fitted into `rect` without distorting it.
    static func path(in rect: CGRect) -> Path {
        let scale = min(rect.width / aspect, rect.height)
        let size = CGSize(width: scale * aspect, height: scale)
        let origin = CGPoint(x: rect.midX - size.width / 2, y: rect.midY - size.height / 2)

        var path = Path()
        for shape in shapes {
            guard shape.count >= 8 else { continue }

            func point(_ index: Int) -> CGPoint {
                CGPoint(
                    x: origin.x + shape[index] * size.width,
                    y: origin.y + shape[index + 1] * size.height
                )
            }

            path.move(to: point(0))
            var index = 2
            while index + 5 < shape.count {
                path.addCurve(to: point(index + 4), control1: point(index), control2: point(index + 2))
                index += 6
            }
            path.closeSubpath()
        }
        return path
    }

    /// One shape, fitted the same way — for drawing them individually so each
    /// can move on its own.
    static func path(forShape index: Int, in rect: CGRect) -> Path {
        guard shapes.indices.contains(index) else { return Path() }

        var path = Path()
        let shape = shapes[index]
        guard shape.count >= 8 else { return path }

        func point(_ offset: Int) -> CGPoint {
            CGPoint(
                x: rect.minX + shape[offset] * rect.width,
                y: rect.minY + shape[offset + 1] * rect.height
            )
        }

        path.move(to: point(0))
        var offset = 2
        while offset + 5 < shape.count {
            path.addCurve(to: point(offset + 4), control1: point(offset), control2: point(offset + 2))
            offset += 6
        }
        path.closeSubpath()
        return path
    }
}
